# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 62973fadb5a9f2be09d02fa689f151ed75c78d0d4cb7e086c0749f05d3123ade48ff5ce9b5ab6382a55e6588273f257af8f7e09fba5ac2da76cba7b02c99a8d7

test:
  secret_key_base: a063648a113591d3529bdcdad59314df6565c0b6154983c19b4c59d6c5ad02dc6c8ee64c65f6f300065d3b369b52ac3dc7a8dc88a8761d629d21b9c6c5912ca3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
